# Generated by Django 3.1.6 on 2021-02-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('Cars', models.CharField(max_length=30)),
                ('Bikes', models.CharField(max_length=30)),
                ('Food', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=30)),
                ('Fruit', models.CharField(max_length=30)),
                ('Laptops', models.CharField(max_length=30)),
                ('Mountains', models.CharField(max_length=30)),
                ('Rivers', models.CharField(max_length=30)),
            ],
        ),
    ]
