# Generated by Django 3.1.6 on 2021-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Bikes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Cars',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Food',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Fruit',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Laptops',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Mountains',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Rivers',
        ),
        migrations.AddField(
            model_name='choice',
            name='choices',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
