# Generated by Django 3.1.3 on 2021-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210227_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='PhoneNo',
            field=models.BigIntegerField(),
        ),
    ]
